### ISSUE TITLE
Help needed on how to use on my Raspberry Pi

### ISSUE THREAD

**Issue by GreenTurtwig** [cecolon/ueradio-volumed#1]
I'm interested in this to control my UE Radio from my Raspberry Pi 3 but unfortunately have no idea on how to use it. Would appreciate any help. :-)

**Comment by stiansoevik** [comment]
Try the following command from terminal:

```
echo <command> | nc <UE Radio IP> 1337
```

e.g. `echo unmute | nc 192.168.0.123 1337`

**Comment by GreenTurtwig** [comment]
Thanks for the help. :-)
I've entered `bash volumed.sh echo mute | nc 192.168.0.4 1337` into the terminal after I've `cd` into the folder multiple times and nothing is happening, no text output or anything (since it looks like it's meant to `echo` "Received command: "). Tried a few other variations of the command in case something was wrong but still nothing.
I'm a bit of a Linux noob so I guess that doesn't help much, but I'm determined to get this to work. :-P

**Comment by stiansoevik** [comment]
volumed.sh must run on the UE radio.
The commands I provided, can run from another computer (e.g. your Raspberry Pi).

**Comment by GreenTurtwig** [comment]
Ahh, I think I understand what everything does now. :-)
Do you have any idea how I might go about running it on the radio?

**Comment by stiansoevik** [comment]
ssh to the radio as root (search for how to enable, I think it might be
called developer mode or something)
download the script (see if wget is installed, if not, copy the text, type
"cat > volumed.sh", paste in the ssh client and press ctrl+d)
make it executable (chmod +x volumed.sh)
start it (./volumed.sh)

Happy hacking :)

**Comment by GreenTurtwig** [comment]
Thanks alot! :-)
I guess you can close the issue now. :-P
